### ISSUE TITLE
 uCommonUtils.pas unit is missing

### ISSUE THREAD

**Issue by BoronZhang** [theprogrammer67/HikvisionDelphi#2]
Hi brother, can you provide uCommonUtils unit? The file is missing for project VideoDeviceTest.

**Comment by theprogrammer67** [comment]
Good afternoon.
I added the file and updated the repository.
I also added another repository: https://github.com/theprogrammer67/vr_hikvision1c83n
Unfortunately, this project was not completed due to the fault of the customer.
I hope my work is of some help to you!
Good luck!

**Comment by BoronZhang** [comment]
Good afternoon brother. Thanks a lot!!!
